import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type LangCode = "en" | "hi" | "de" | "ru" | "fr";

export interface Language {
  code: LangCode;
  label: string;
  flag: string;
  nativeName: string;
}

export const LANGUAGES: Language[] = [
  { code: "en", label: "English",  flag: "🇺🇸", nativeName: "English"  },
  { code: "hi", label: "Hindi",    flag: "🇮🇳", nativeName: "हिन्दी"   },
  { code: "de", label: "German",   flag: "🇩🇪", nativeName: "Deutsch"  },
  { code: "ru", label: "Russian",  flag: "🇷🇺", nativeName: "Русский"  },
  { code: "fr", label: "French",   flag: "🇫🇷", nativeName: "Français" },
];

const T: Record<LangCode, Record<string, string>> = {
  en: {
    // ─── Navigation ───────────────────────────────
    dashboard:      "Dashboard",
    rentNumber:     "Rent Number",
    myRentals:      "My Rentals",
    plansBilling:   "Plans & Billing",
    referrals:      "Referrals",
    apiDocs:        "API & Docs",
    settings:       "Settings",
    support:        "Support",
    addFunds:       "Top up balance",
    search:         "Search",
    signOut:        "Sign Out",
    online:         "Online",
    admin:          "Admin",
    // ─── Dashboard ────────────────────────────────
    welcomeBack:    "Welcome back",
    walletBalance:  "Wallet Balance",
    totalSpent:     "Total Spent",
    activeRentals:  "Active Rentals",
    recentActivity: "Recent Activity",
    noActiveRentals:"No active rentals yet",
    getRentNow:     "Rent a Number",
    viewAllRentals: "View All Rentals",
    smsReceived:    "SMS Received",
    topUp:          "Top Up",
    quickActions:   "Quick Actions",
    rentedNumber:   "Rented Number",
    expires:        "Expires",
    // ─── Rent page ────────────────────────────────
    rentANumber:    "Rent a Number",
    selectService:  "Select Service",
    selectCountry:  "Select Country",
    inStock:        "in stock",
    rentNow:        "Rent Now",
    confirmRent:    "Confirm Rental",
    insufficientBalance: "Insufficient balance. Top up to continue.",
    priceLabel:     "Price",
    noServices:     "No services are enabled yet.",
    searchService:  "Search service…",
    searchCountry:  "Search country…",
    sortByStock:    "Sort by Stock",
    sortByPrice:    "Sort by Price",
    availability:   "Availability",
    // ─── Rentals page ─────────────────────────────
    filterAll:      "All",
    filterActive:   "Active",
    filterCompleted:"Completed",
    filterCancelled:"Cancelled",
    expiresIn:      "Expires in",
    copyNumber:     "Copy Number",
    refreshSms:     "Refresh SMS",
    cancelRental:   "Cancel",
    noRentals:      "No rentals found.",
    viewSms:        "View SMS",
    number:         "Number",
    service:        "Service",
    country:        "Country",
    status:         "Status",
    actions:        "Actions",
    // ─── Payments ─────────────────────────────────
    plansAndBilling:"Plans & Billing",
    topUpBalance:   "Top Up Balance",
    selectPackage:  "Select a Package",
    payNow:         "Pay Now",
    payWith:        "Pay with",
    transactionHistory: "Transaction History",
    noPayments:     "No transactions yet.",
    amountLabel:    "Amount",
    dateLabel:      "Date",
    paid:           "Paid",
    pending:        "Processing",
    failed:         "Failed",
    customAmount:   "Custom Amount",
    // ─── Settings ─────────────────────────────────
    settingsTitle:  "Settings",
    profileSection: "Profile",
    apiKeysSection: "API Keys",
    languageSection:"Language",
    yourAccount:    "Your Account",
    createApiKey:   "Create Key",
    deleteApiKey:   "Delete",
    noApiKeys:      "No API keys yet.",
    keyName:        "Key Name",
    lastUsed:       "Last used",
    never:          "Never",
    security:       "Security",
    saveChanges:    "Save Changes",
    cancel:         "Cancel",
    // ─── Support ──────────────────────────────────
    supportTitle:   "Support",
    newTicket:      "New Ticket",
    ticketSubject:  "Subject",
    ticketCategory: "Category",
    ticketMessage:  "Message",
    submitTicket:   "Submit Ticket",
    openStatus:     "Open",
    inProgressStatus: "In Progress",
    resolvedStatus: "Resolved",
    closedStatus:   "Closed",
    noTickets:      "No support tickets yet.",
    replyMessage:   "Send Reply",
    typeMessage:    "Type a message…",
    // ─── Common ───────────────────────────────────
    loading:        "Loading…",
    error:          "Something went wrong.",
    retry:          "Retry",
    close:          "Close",
    noData:         "No data available.",
    save:           "Save",
    copied:         "Copied!",
    balance:        "Balance",
    credits:        "Credits",
    free:           "Free",
    popular:        "Popular",
    copy:           "Copy",
    view:           "View",
    delete:         "Delete",
    create:         "Create",
    submit:         "Submit",
    back:           "Back",
    next:           "Next",
    or:             "or",
  },

  hi: {
    // ─── Navigation ───────────────────────────────
    dashboard:      "डैशबोर्ड",
    rentNumber:     "नंबर किराए पर",
    myRentals:      "मेरे किराये",
    plansBilling:   "योजनाएं और बिलिंग",
    referrals:      "रेफरल",
    apiDocs:        "API और डॉक्स",
    settings:       "सेटिंग्स",
    support:        "सहायता",
    addFunds:       "बैलेंस टॉप अप",
    search:         "खोजें",
    signOut:        "साइन आउट",
    online:         "ऑनलाइन",
    admin:          "एडमिन",
    // ─── Dashboard ────────────────────────────────
    welcomeBack:    "वापस स्वागत है",
    walletBalance:  "वॉलेट बैलेंस",
    totalSpent:     "कुल खर्च",
    activeRentals:  "सक्रिय किराये",
    recentActivity: "हाल की गतिविधि",
    noActiveRentals:"अभी कोई सक्रिय किराया नहीं",
    getRentNow:     "नंबर किराए पर लें",
    viewAllRentals: "सभी किराये देखें",
    smsReceived:    "SMS प्राप्त हुआ",
    topUp:          "टॉप अप",
    quickActions:   "त्वरित क्रियाएं",
    rentedNumber:   "किराए का नंबर",
    expires:        "समाप्त होता है",
    // ─── Rent page ────────────────────────────────
    rentANumber:    "एक नंबर किराए पर लें",
    selectService:  "सेवा चुनें",
    selectCountry:  "देश चुनें",
    inStock:        "स्टॉक में",
    rentNow:        "अभी किराए पर लें",
    confirmRent:    "किराया पुष्टि करें",
    insufficientBalance: "अपर्याप्त बैलेंस। जारी रखने के लिए टॉप अप करें।",
    priceLabel:     "कीमत",
    noServices:     "अभी कोई सेवा सक्षम नहीं है।",
    searchService:  "सेवा खोजें…",
    searchCountry:  "देश खोजें…",
    sortByStock:    "स्टॉक के अनुसार",
    sortByPrice:    "कीमत के अनुसार",
    availability:   "उपलब्धता",
    // ─── Rentals page ─────────────────────────────
    filterAll:      "सभी",
    filterActive:   "सक्रिय",
    filterCompleted:"पूर्ण",
    filterCancelled:"रद्द",
    expiresIn:      "में समाप्त",
    copyNumber:     "नंबर कॉपी करें",
    refreshSms:     "SMS रीफ्रेश",
    cancelRental:   "रद्द करें",
    noRentals:      "कोई किराया नहीं मिला।",
    viewSms:        "SMS देखें",
    number:         "नंबर",
    service:        "सेवा",
    country:        "देश",
    status:         "स्थिति",
    actions:        "क्रियाएं",
    // ─── Payments ─────────────────────────────────
    plansAndBilling:"योजनाएं और बिलिंग",
    topUpBalance:   "बैलेंस टॉप अप करें",
    selectPackage:  "पैकेज चुनें",
    payNow:         "अभी भुगतान करें",
    payWith:        "भुगतान करें",
    transactionHistory: "लेनदेन इतिहास",
    noPayments:     "अभी कोई लेनदेन नहीं।",
    amountLabel:    "राशि",
    dateLabel:      "तारीख",
    paid:           "भुगतान किया",
    pending:        "प्रक्रियाधीन",
    failed:         "विफल",
    customAmount:   "कस्टम राशि",
    // ─── Settings ─────────────────────────────────
    settingsTitle:  "सेटिंग्स",
    profileSection: "प्रोफाइल",
    apiKeysSection: "API कुंजियाँ",
    languageSection:"भाषा",
    yourAccount:    "आपका खाता",
    createApiKey:   "कुंजी बनाएं",
    deleteApiKey:   "हटाएं",
    noApiKeys:      "अभी कोई API कुंजी नहीं।",
    keyName:        "कुंजी का नाम",
    lastUsed:       "अंतिम उपयोग",
    never:          "कभी नहीं",
    security:       "सुरक्षा",
    saveChanges:    "बदलाव सहेजें",
    cancel:         "रद्द करें",
    // ─── Support ──────────────────────────────────
    supportTitle:   "सहायता",
    newTicket:      "नया टिकट",
    ticketSubject:  "विषय",
    ticketCategory: "श्रेणी",
    ticketMessage:  "संदेश",
    submitTicket:   "टिकट सबमिट करें",
    openStatus:     "खुला",
    inProgressStatus: "प्रगति में",
    resolvedStatus: "हल हो गया",
    closedStatus:   "बंद",
    noTickets:      "अभी कोई समर्थन टिकट नहीं।",
    replyMessage:   "उत्तर भेजें",
    typeMessage:    "संदेश टाइप करें…",
    // ─── Common ───────────────────────────────────
    loading:        "लोड हो रहा है…",
    error:          "कुछ गलत हो गया।",
    retry:          "पुन: प्रयास करें",
    close:          "बंद करें",
    noData:         "कोई डेटा उपलब्ध नहीं।",
    save:           "सहेजें",
    copied:         "कॉपी हो गया!",
    balance:        "बैलेंस",
    credits:        "क्रेडिट",
    free:           "मुफ्त",
    popular:        "लोकप्रिय",
    copy:           "कॉपी",
    view:           "देखें",
    delete:         "हटाएं",
    create:         "बनाएं",
    submit:         "सबमिट",
    back:           "वापस",
    next:           "अगला",
    or:             "या",
  },

  de: {
    // ─── Navigation ───────────────────────────────
    dashboard:      "Dashboard",
    rentNumber:     "Nummer mieten",
    myRentals:      "Meine Mieten",
    plansBilling:   "Pläne & Abrechnung",
    referrals:      "Empfehlungen",
    apiDocs:        "API & Docs",
    settings:       "Einstellungen",
    support:        "Support",
    addFunds:       "Guthaben aufladen",
    search:         "Suchen",
    signOut:        "Abmelden",
    online:         "Online",
    admin:          "Admin",
    // ─── Dashboard ────────────────────────────────
    welcomeBack:    "Willkommen zurück",
    walletBalance:  "Wallet-Guthaben",
    totalSpent:     "Gesamtausgaben",
    activeRentals:  "Aktive Mieten",
    recentActivity: "Letzte Aktivitäten",
    noActiveRentals:"Noch keine aktiven Mieten",
    getRentNow:     "Nummer mieten",
    viewAllRentals: "Alle Mieten anzeigen",
    smsReceived:    "SMS erhalten",
    topUp:          "Aufladen",
    quickActions:   "Schnellaktionen",
    rentedNumber:   "Gemietete Nummer",
    expires:        "Läuft ab",
    // ─── Rent page ────────────────────────────────
    rentANumber:    "Nummer mieten",
    selectService:  "Dienst auswählen",
    selectCountry:  "Land auswählen",
    inStock:        "vorrätig",
    rentNow:        "Jetzt mieten",
    confirmRent:    "Miete bestätigen",
    insufficientBalance: "Unzureichendes Guthaben. Bitte aufladen.",
    priceLabel:     "Preis",
    noServices:     "Noch keine Dienste aktiviert.",
    searchService:  "Dienst suchen…",
    searchCountry:  "Land suchen…",
    sortByStock:    "Nach Bestand sortieren",
    sortByPrice:    "Nach Preis sortieren",
    availability:   "Verfügbarkeit",
    // ─── Rentals page ─────────────────────────────
    filterAll:      "Alle",
    filterActive:   "Aktiv",
    filterCompleted:"Abgeschlossen",
    filterCancelled:"Storniert",
    expiresIn:      "Läuft ab in",
    copyNumber:     "Nummer kopieren",
    refreshSms:     "SMS aktualisieren",
    cancelRental:   "Stornieren",
    noRentals:      "Keine Mieten gefunden.",
    viewSms:        "SMS anzeigen",
    number:         "Nummer",
    service:        "Dienst",
    country:        "Land",
    status:         "Status",
    actions:        "Aktionen",
    // ─── Payments ─────────────────────────────────
    plansAndBilling:"Pläne & Abrechnung",
    topUpBalance:   "Guthaben aufladen",
    selectPackage:  "Paket auswählen",
    payNow:         "Jetzt bezahlen",
    payWith:        "Zahlen mit",
    transactionHistory: "Transaktionsverlauf",
    noPayments:     "Noch keine Transaktionen.",
    amountLabel:    "Betrag",
    dateLabel:      "Datum",
    paid:           "Bezahlt",
    pending:        "In Bearbeitung",
    failed:         "Fehlgeschlagen",
    customAmount:   "Benutzerdefinierter Betrag",
    // ─── Settings ─────────────────────────────────
    settingsTitle:  "Einstellungen",
    profileSection: "Profil",
    apiKeysSection: "API-Schlüssel",
    languageSection:"Sprache",
    yourAccount:    "Ihr Konto",
    createApiKey:   "Schlüssel erstellen",
    deleteApiKey:   "Löschen",
    noApiKeys:      "Noch keine API-Schlüssel.",
    keyName:        "Schlüsselname",
    lastUsed:       "Zuletzt verwendet",
    never:          "Nie",
    security:       "Sicherheit",
    saveChanges:    "Änderungen speichern",
    cancel:         "Abbrechen",
    // ─── Support ──────────────────────────────────
    supportTitle:   "Support",
    newTicket:      "Neues Ticket",
    ticketSubject:  "Betreff",
    ticketCategory: "Kategorie",
    ticketMessage:  "Nachricht",
    submitTicket:   "Ticket einreichen",
    openStatus:     "Offen",
    inProgressStatus: "In Bearbeitung",
    resolvedStatus: "Gelöst",
    closedStatus:   "Geschlossen",
    noTickets:      "Noch keine Support-Tickets.",
    replyMessage:   "Antwort senden",
    typeMessage:    "Nachricht eingeben…",
    // ─── Common ───────────────────────────────────
    loading:        "Wird geladen…",
    error:          "Etwas ist schiefgelaufen.",
    retry:          "Wiederholen",
    close:          "Schließen",
    noData:         "Keine Daten verfügbar.",
    save:           "Speichern",
    copied:         "Kopiert!",
    balance:        "Guthaben",
    credits:        "Credits",
    free:           "Kostenlos",
    popular:        "Beliebt",
    copy:           "Kopieren",
    view:           "Anzeigen",
    delete:         "Löschen",
    create:         "Erstellen",
    submit:         "Absenden",
    back:           "Zurück",
    next:           "Weiter",
    or:             "oder",
  },

  ru: {
    // ─── Navigation ───────────────────────────────
    dashboard:      "Панель",
    rentNumber:     "Арендовать номер",
    myRentals:      "Мои аренды",
    plansBilling:   "Тарифы и оплата",
    referrals:      "Рефералы",
    apiDocs:        "API и документы",
    settings:       "Настройки",
    support:        "Поддержка",
    addFunds:       "Пополнить баланс",
    search:         "Поиск",
    signOut:        "Выйти",
    online:         "Онлайн",
    admin:          "Админ",
    // ─── Dashboard ────────────────────────────────
    welcomeBack:    "С возвращением",
    walletBalance:  "Баланс кошелька",
    totalSpent:     "Всего потрачено",
    activeRentals:  "Активные аренды",
    recentActivity: "Последняя активность",
    noActiveRentals:"Нет активных аренд",
    getRentNow:     "Арендовать номер",
    viewAllRentals: "Все аренды",
    smsReceived:    "SMS получено",
    topUp:          "Пополнить",
    quickActions:   "Быстрые действия",
    rentedNumber:   "Арендованный номер",
    expires:        "Истекает",
    // ─── Rent page ────────────────────────────────
    rentANumber:    "Арендовать номер",
    selectService:  "Выбрать сервис",
    selectCountry:  "Выбрать страну",
    inStock:        "в наличии",
    rentNow:        "Арендовать",
    confirmRent:    "Подтвердить аренду",
    insufficientBalance: "Недостаточно средств. Пополните баланс.",
    priceLabel:     "Цена",
    noServices:     "Нет доступных сервисов.",
    searchService:  "Поиск сервиса…",
    searchCountry:  "Поиск страны…",
    sortByStock:    "По наличию",
    sortByPrice:    "По цене",
    availability:   "Доступность",
    // ─── Rentals page ─────────────────────────────
    filterAll:      "Все",
    filterActive:   "Активные",
    filterCompleted:"Завершённые",
    filterCancelled:"Отменённые",
    expiresIn:      "Истекает через",
    copyNumber:     "Копировать номер",
    refreshSms:     "Обновить SMS",
    cancelRental:   "Отменить",
    noRentals:      "Аренды не найдены.",
    viewSms:        "Просмотр SMS",
    number:         "Номер",
    service:        "Сервис",
    country:        "Страна",
    status:         "Статус",
    actions:        "Действия",
    // ─── Payments ─────────────────────────────────
    plansAndBilling:"Тарифы и оплата",
    topUpBalance:   "Пополнить баланс",
    selectPackage:  "Выбрать пакет",
    payNow:         "Оплатить",
    payWith:        "Оплатить через",
    transactionHistory: "История транзакций",
    noPayments:     "Транзакций пока нет.",
    amountLabel:    "Сумма",
    dateLabel:      "Дата",
    paid:           "Оплачено",
    pending:        "Обрабатывается",
    failed:         "Ошибка",
    customAmount:   "Своя сумма",
    // ─── Settings ─────────────────────────────────
    settingsTitle:  "Настройки",
    profileSection: "Профиль",
    apiKeysSection: "API-ключи",
    languageSection:"Язык",
    yourAccount:    "Ваш аккаунт",
    createApiKey:   "Создать ключ",
    deleteApiKey:   "Удалить",
    noApiKeys:      "API-ключей пока нет.",
    keyName:        "Название ключа",
    lastUsed:       "Последнее использование",
    never:          "Никогда",
    security:       "Безопасность",
    saveChanges:    "Сохранить изменения",
    cancel:         "Отмена",
    // ─── Support ──────────────────────────────────
    supportTitle:   "Поддержка",
    newTicket:      "Новый тикет",
    ticketSubject:  "Тема",
    ticketCategory: "Категория",
    ticketMessage:  "Сообщение",
    submitTicket:   "Отправить тикет",
    openStatus:     "Открыт",
    inProgressStatus: "В работе",
    resolvedStatus: "Решён",
    closedStatus:   "Закрыт",
    noTickets:      "Тикетов поддержки пока нет.",
    replyMessage:   "Отправить ответ",
    typeMessage:    "Введите сообщение…",
    // ─── Common ───────────────────────────────────
    loading:        "Загрузка…",
    error:          "Что-то пошло не так.",
    retry:          "Повторить",
    close:          "Закрыть",
    noData:         "Данных нет.",
    save:           "Сохранить",
    copied:         "Скопировано!",
    balance:        "Баланс",
    credits:        "Кредиты",
    free:           "Бесплатно",
    popular:        "Популярное",
    copy:           "Копировать",
    view:           "Просмотр",
    delete:         "Удалить",
    create:         "Создать",
    submit:         "Отправить",
    back:           "Назад",
    next:           "Далее",
    or:             "или",
  },

  fr: {
    // ─── Navigation ───────────────────────────────
    dashboard:      "Tableau de bord",
    rentNumber:     "Louer un numéro",
    myRentals:      "Mes locations",
    plansBilling:   "Plans et facturation",
    referrals:      "Parrainages",
    apiDocs:        "API et docs",
    settings:       "Paramètres",
    support:        "Assistance",
    addFunds:       "Recharger le solde",
    search:         "Rechercher",
    signOut:        "Se déconnecter",
    online:         "En ligne",
    admin:          "Admin",
    // ─── Dashboard ────────────────────────────────
    welcomeBack:    "Content de vous revoir",
    walletBalance:  "Solde du portefeuille",
    totalSpent:     "Total dépensé",
    activeRentals:  "Locations actives",
    recentActivity: "Activité récente",
    noActiveRentals:"Pas encore de locations actives",
    getRentNow:     "Louer un numéro",
    viewAllRentals: "Voir toutes les locations",
    smsReceived:    "SMS reçu",
    topUp:          "Recharger",
    quickActions:   "Actions rapides",
    rentedNumber:   "Numéro loué",
    expires:        "Expire",
    // ─── Rent page ────────────────────────────────
    rentANumber:    "Louer un numéro",
    selectService:  "Choisir un service",
    selectCountry:  "Choisir un pays",
    inStock:        "en stock",
    rentNow:        "Louer maintenant",
    confirmRent:    "Confirmer la location",
    insufficientBalance: "Solde insuffisant. Rechargez pour continuer.",
    priceLabel:     "Prix",
    noServices:     "Aucun service activé.",
    searchService:  "Rechercher un service…",
    searchCountry:  "Rechercher un pays…",
    sortByStock:    "Trier par stock",
    sortByPrice:    "Trier par prix",
    availability:   "Disponibilité",
    // ─── Rentals page ─────────────────────────────
    filterAll:      "Tous",
    filterActive:   "Actif",
    filterCompleted:"Terminé",
    filterCancelled:"Annulé",
    expiresIn:      "Expire dans",
    copyNumber:     "Copier le numéro",
    refreshSms:     "Actualiser SMS",
    cancelRental:   "Annuler",
    noRentals:      "Aucune location trouvée.",
    viewSms:        "Voir SMS",
    number:         "Numéro",
    service:        "Service",
    country:        "Pays",
    status:         "Statut",
    actions:        "Actions",
    // ─── Payments ─────────────────────────────────
    plansAndBilling:"Plans et facturation",
    topUpBalance:   "Recharger le solde",
    selectPackage:  "Choisir un forfait",
    payNow:         "Payer maintenant",
    payWith:        "Payer avec",
    transactionHistory: "Historique des transactions",
    noPayments:     "Pas encore de transactions.",
    amountLabel:    "Montant",
    dateLabel:      "Date",
    paid:           "Payé",
    pending:        "En cours",
    failed:         "Échoué",
    customAmount:   "Montant personnalisé",
    // ─── Settings ─────────────────────────────────
    settingsTitle:  "Paramètres",
    profileSection: "Profil",
    apiKeysSection: "Clés API",
    languageSection:"Langue",
    yourAccount:    "Votre compte",
    createApiKey:   "Créer une clé",
    deleteApiKey:   "Supprimer",
    noApiKeys:      "Pas encore de clés API.",
    keyName:        "Nom de la clé",
    lastUsed:       "Dernière utilisation",
    never:          "Jamais",
    security:       "Sécurité",
    saveChanges:    "Enregistrer",
    cancel:         "Annuler",
    // ─── Support ──────────────────────────────────
    supportTitle:   "Assistance",
    newTicket:      "Nouveau ticket",
    ticketSubject:  "Sujet",
    ticketCategory: "Catégorie",
    ticketMessage:  "Message",
    submitTicket:   "Soumettre le ticket",
    openStatus:     "Ouvert",
    inProgressStatus: "En cours",
    resolvedStatus: "Résolu",
    closedStatus:   "Fermé",
    noTickets:      "Pas encore de tickets.",
    replyMessage:   "Envoyer une réponse",
    typeMessage:    "Tapez un message…",
    // ─── Common ───────────────────────────────────
    loading:        "Chargement…",
    error:          "Une erreur est survenue.",
    retry:          "Réessayer",
    close:          "Fermer",
    noData:         "Aucune donnée disponible.",
    save:           "Enregistrer",
    copied:         "Copié !",
    balance:        "Solde",
    credits:        "Crédits",
    free:           "Gratuit",
    popular:        "Populaire",
    copy:           "Copier",
    view:           "Voir",
    delete:         "Supprimer",
    create:         "Créer",
    submit:         "Soumettre",
    back:           "Retour",
    next:           "Suivant",
    or:             "ou",
  },
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (code: LangCode) => void;
  t: (key: string) => string;
  current: Language;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
  current: LANGUAGES[0],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => {
    try { return (localStorage.getItem("skysms-lang") as LangCode) || "en"; } catch { return "en"; }
  });

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = (code: LangCode) => {
    setLangState(code);
    try { localStorage.setItem("skysms-lang", code); } catch {}
  };

  const t = (key: string): string => T[lang]?.[key] ?? T.en[key] ?? key;
  const current = LANGUAGES.find(l => l.code === lang) ?? LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, current }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
